spring:
  cloud:
    stream:
      bindings:
        userDeleted-out-0:
          destination: users.delete
  application:
    name: user-service
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka