on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kwetterbdb.azurecr.io
        username: ${{ secrets.acr_kwetterbdb_username }}
        password: ${{ secrets.acr_kwetterbdb_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kwetterbdb.azurecr.io/kwetter:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push kwetterbdb.azurecr.io/kwetter:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kwetter_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kwetter-user-service | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kwetter-user-service`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kwetter-user-service
        container-registry-url: kwetterbdb.azurecr.io
        container-registry-username: ${{ secrets.acr_kwetterbdb_username }}
        container-registry-password: ${{ secrets.acr_kwetterbdb_password }}
        secret-name: kwetterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kwetter-user-service
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kwetterbdb.azurecr.io/kwetter:${{ github.sha }}
        imagepullsecrets: |
          kwetterdockerauth
